build:
  maxIssues: 0
  excludeCorrectable: true

config:
  validation: true

style:
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2']
  WildcardImport:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120

formatting:
  active: true
  android: true
  autoCorrect: false
  FinalNewline:
    active: true
  Indentation:
    active: true
    indentSize: 4
    continuationIndentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 120
